config/routes.rb
Rails.application.routes.draw do
  root to: 'rooms#show'
  resources 'messages', only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self }
  after_destroy_commit { MessageDestroyJob.perform_later self.id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    Message.create! message_params
    head :no_content
  end

  def destroy
    Message.find(params[:id]).destroy!
  end

  protected

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @messages = Message.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finances</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.slim
.message data-id=message.id
  .pull-xs-left
    p = message.content
  .pull-xs-right
    = link_to 'remove', message_path(message), method: :delete, class: 'btn btn-danger', confirm: 'Delete?', remote: true
.clearfix

app/views/rooms/show.html.slim
.container
  .row
    h1 Chat room
    #messages
      = render @messages
    hr
    = form_for Message.new, remote: true, html: { class: 'form js-chat-form' } do |f|
      fieldset.form-group
        = f.text_field :content, class: 'form-control'
      button type="submit" class="btn btn-primary" Submit